### ISSUE TITLE
Acknowledging the status quo and more examples of the benefits. 

### ISSUE THREAD

**Issue by roboton** [agency-fund/r-workshop#2]
https://github.com/agency-fund/r-workshop/blob/b1e9982ec1b0227da467989b01477dc96e0734d3/slides/version-control-long.Rmd#L372

I think sometimes this type of presentation misses because organizations feel like they have a good alternative to version control, reversions, parallel work streams, etc.

It almost always makes sense when working on large multi-person software systems but it's not as clear when it comes to one-to-few person analyses.  

Maybe worth showing a good example of `git blame` which visualizes who is responsible for which lines of codes.

Also ensure to highlight the use of commit messages to get a textual history of what happened with the file.

**Comment by littlehifive** [comment]
Thanks! I added two screenshots on commit history and the blame view on GitHub. See updated slides [here](https://github.com/agency-fund/r-workshop/blob/main/slides/version-control-long.pdf).
